const errorCodes = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    FUNCTION_NOT_FOUND: 'FUNCTION_NOT_FOUND',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    INVALID_OBJECT_ID: 'INVALID_OBJECT_ID',
    INVALID_DATA: 'INVALID_DATA',
    INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    DATA_ALREADY_VERIFIED: 'DATA_ALREADY_VERIFIED',
    DATA_ALREADY_EXISTS: 'DATA_ALREADY_EXISTS',
    DATA_VERIFIED_NOT_FOUND: 'DATA_VERIFIED_NOT_FOUND',
    DATA_VERIFIED_EXPIRED: 'DATA_VERIFIED_EXPIRED',
    DATA_VERIFIED_INCORRECT: 'DATA_VERIFIED_INCORRECT',
    DATA_PENDING_TO_CONFIRM: 'DATA_PENDING_TO_CONFIRM',
    DATA_ID_REQUIRED: 'DATA_ID_REQUIRED',
    DATA_INVALID_FORMAT: 'DATA_INVALID_FORMAT',
    DUPLICATE_CREDENTIALS: 'DUPLICATE_CREDENTIALS',
    MISSING_AUTH_COOKIE: 'MISSING_AUTH_COOKIE'
};

module.exports = errorCodes;